### ISSUE TITLE
How to configure wifi password

### ISSUE THREAD

**Issue by axelclark** [nerves-project/nerves_interim_wifi#15]
This is just a suggestion, but it might be a good idea to include the best practice for saving your wifi password.  Right now the example shows plain text which is probably a good way to make sure you can get it working.  However, some people may not think about leaving it hard coded and pushing their project up to GitHub with their home wifi password.  

This is how I configured it, but there might be a better way.

Prior to pushing your project to GitHub, you should change the config.ex to use an environmental variable for your wifi password.  For example:
`psk: System.get_env("WIFI_PASSWORD")`
Then make sure to set the environmental variable in your shell:
`export WIFI_PASSWORD=secret`

**Comment by GregMefford** [comment]
I agree that your recommended method would be a much better example of how to do it properly. 
If you (or someone else) would like to take a stab at a pull request on https://github.com/nerves-project/nerves-examples/blob/master/hello_wifi/, it would be great!

I suggest changing [the config](https://github.com/nerves-project/nerves-examples/blob/master/hello_wifi/config/config.exs) to look for `NERVES_WIFI_SSID` and `NERVES_WIFI_PSK` environment variables and also updating [the README](https://github.com/nerves-project/nerves-examples/blob/master/hello_wifi/README.md) so that it describes how to `export` the environment variables prior to doing `mix firmware`.

**Comment by axelclark** [comment]
@GregMefford I'll work on a PR with your suggestions.

**Comment by GregMefford** [comment]
Thanks again for the PR!
